apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
spec:
  replicas: 2
  selector: { matchLabels: { app: myapp, color: blue } }
  template:
    metadata:
      labels: { app: myapp, color: blue }
    spec:
      containers:
      - name: myapp
        image: mydockerhubuser/myapp:1.0
        ports: [{ containerPort: 3000 }]
